version: '2'
services:
  web:
    build: ./web
    command: nodemon /usr/app/bin/www
    volumes:
      - ./web:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - classifier
  classifier:
    build: ./classifier
    command: python /code/app.py
    volumes:
      - ./classifier:/code
    ports:
      - "5001:80"
